name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm git-publish 
      env:
        CI: true
        MONGO_URI: mongodb://admin:tripster1@ds137631.mlab.com:37631/trippy
        JWT_SECRET: mischief_managed
        JWT_EXPIRATION_MINUTES: 43200
        NODE_ENV: production
        JOB_TYPES: notifs
        FCM_SERVER_KEY: AAAAv5jEgow:APA91bGTN8YjGQ8i-L0e-UEN_Ua9aZdFXat_RG7SeEGCt6oOu0vvSUkQTTiJvW5GiqR7P8EuRJEebxtIe_degxGb-WaT-4sAWp5cAa-dneei34o1myyUgHOZSOap1hnBnGsFztBxHIRQ
